---
patching:
  author: "Will Tome"
  category: infrastructure
  name: "SERVER / Patching"
  description: "patching for Linux servers"
  job_type: "run"
  inventory: "Workshop Inventory"
  playbook: "playbooks/02_patching.yml"
  credential: "Workshop Credential"
  survey_enabled: true
  survey_spec:
    name: ''
    description: ''
    spec:
      - question_name: 'Enter host to configure'
        type: text
        variable: HOSTS
        required: false
  project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Buisness Unit"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/product-demos"
  workshop_type:
    - f5
    - rhel
    - rhel_90
