---
hardening:
  author: "Will Tome"
  category: security
  name: "SERVER / Hardening"
  description: "hardening for Linux servers"
  job_type: "run"
  inventory: "Workshop Inventory"
  playbook: "playbooks/03_hardening.yml"
  credential: "Workshop Credential"
  survey_enabled: true
  survey_spec:
    name: ''
    description: ''
    spec:
      - question_name: 'Enter host to configure'
        type: text
        variable: HOSTS
        required: false
      - question_name: Configure Firewall?
        type: multiplechoice
        variable: harden_firewall
        required: false
        choices:
          - 'Yes'
          - 'No'
      - question_name: Configure Time?
        type: multiplechoice
        variable: harden_time
        required: false
        choices:
          - 'Yes'
          - 'No'
      - question_name: Harden SSH?
        type: multiplechoice
        variable: harden_ssh
        required: false
        choices:
          - 'Yes'
          - 'No'
      - question_name: PCI Baseline?
        type: multiplechoice
        variable: harden_pci
        required: false
        choices:
          - 'Yes'
          - 'No'
  project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Buisness Unit"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/product-demos"
  workshop_type:
    - f5
    - rhel
    - rhel_90
