---
debug_info:
  author: "Will Tome"
  category: infrastructure
  name: "SERVER / Gather Debug Info"
  description: "provide info for memory and CPU usage for specified systems"
  job_type: "run"
  inventory: "Workshop Inventory"
  playbook: playbooks/06_debug_info.yml
  credential: "Workshop Credential"
  survey_enabled: false
  survey_spec:
    name: ''
    description: ''
    spec:
      - question_name: 'Enter host to configure'
        type: text
        variable: HOSTS
        required: false
  project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Buisness Unit"
    organization: "Default"
    scm_type: git
    scm_url: "https://github.com/ansible/product-demos"
  workshop_type:
    - f5
    - rhel
    - rhel_90
