- name: My First Play from Github
  hosts: all
  tasks:
    - name: Doing Ping to Hosts
      ping:
        data: "Received PONG"
    - name: Debuggin Something
      debug:
         msg: "Hello From The Second Tasks Here!!"
